---
roles:
  - name: chriswayg.msmtp-mailer
  - name: rofrantz.duckdns

collections:
  - name: amazon.aws
  - name: community.docker
  - name: community.general
  - name: community.crypto
  - name: ansible.posix